version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: card_db
    environment:
      POSTGRES_DB: card_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - card-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: card_manager_app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/card_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-min-256-bits-here}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY:-your-32-byte-encryption-key-here}
    depends_on:
      - postgres
    networks:
      - card-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  card-network:
    driver: bridge