server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: bank-card-manager
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret-key: "dGhpcy1pcy1hLXN1cGVyLXNlY3JldC1rZXktZm9yLWRldmVsb3BtZW50"
  expiration: 86400000
  refresh-token:
    expiration: 604800000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /api/v3/api-docs/swagger-config
    url: /api/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    info:
      enabled: true

# Добавьте кастомную информацию
info:
  app:
    name: Bank Card Manager
    version: 1.0.0
    description: REST API for bank card management
    developers: Borgex Team
  spring:
    version: 3.2.0
  java:
    version: ${java.version}
logging:
  level:
    org.springframework: DEBUG
    com.example.bankcards: DEBUG
    org.hibernate: ERROR