server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: bank-card-manager
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret-key: "dGhpcy1pcy1hLXN1cGVyLXNlY3JldC1rZXktZm9yLWRldmVsb3BtZW50"
  expiration: 86400000
  refresh-token:
    expiration: 604800000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html